apiVersion: v1
kind: Service
metadata:
  name: postgress
  namespace: weblate
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP
  selector:
    app: postgres