kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weblate
  namespace: weblate
  labels:
    app: weblate 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem